// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CacheBust","status":true,"description":"force plugin reload","parameters":{}},
{"name":"EnemyBattleLayout","status":true,"description":"enemy scale/layout","parameters":{"defaultScale":"70","homeX":"200","homeY":"360","attackStep":"48","useHomeOverride":"true"}},
{"name":"BraveAcademyQuiz","status":true,"description":"Brave Academy Quiz v2.0","parameters":{"quizFolder":"quiz"}}
];
